'''adapted from https://github.com/yangkevin2/naacl-2021-fudge-controlled-generation'''
PAD_TOKEN = '[PAD]'
EOT_TOKEN = '<|endoftext|>'
BOS_TOKEN = '[BOS]'

LANGUAGE_MODEL_STRING = 'gpt2'
BIG_LANGUAGE_MODEL_STRING = 'gpt2-medium'

CLASSIFIER_DROPOUT = 0.1
SEPARATOR = '[SEP]'
ORACLE_NUM_LABELS = 5
NUM_CLASSES = 5 # TODO: change this to LABEL_NUM_CLASSES and LENGTH_NUM_CLASSES separately!

EOT_ID = 50256
# ------------------------------ #

DIR_END_SPLIT_POSITIONS = 32

TOPIC_VAL_SIZE = 100000
FORMALITY_VAL_SIZE = 2000
VOCAB_SIZE = 50000

FORMALITY_MAX_LEN = 200

GLOVE_PRINT_PROGRESS_FREQ = 1000000
GLOVE_DIM = 300
HIDDEN_DIM = 300
RNN_DIM = 150

MIN_SENTENCE_LENGTH = 3

POETRY_LINE_SYLLABLES = 10
MAX_SYLLABLES_PER_WORD = 10 # no way anything is more
MAX_COUNT_SYLLABLE_DIST = 10
MAX_COUNT_SYLLABLE_INPUT_LENGTH = 25 # for just a couplet, shouldn't need more
COUNT_SYLLABLE_DIM = 100
UNKNOWN_RHYME_GROUP = 'UNKNOWN_RHYME_GROUP'
PHRASE_ENDS = '.?!'

POETRY_BANNED_TOKENS = [198, 50256, 628, 220] # newlines and eos and such

